server:
  port: 8080
spring:
  datasource:
    url: jdbc:hsqldb:hsql://localhost/iyzicodb;readonly=true
    driverClassName: org.hsqldb.jdbcDriver
    username: sa
  jpa:
    show-sql: true
    open-in-view: false